---
language: node_js
node_js:
  - "6"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

before_install:
  - npm config set spin false

notifications:
  email:
    on_success: never

branches:
  only:
    - master
    - develop
